name: Docs Update

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      with:
        fetch-depth: 0

    - name: Helm Docs GitHub Action
      uses: losisin/helm-docs-github-action@57d2dc9379d9f0d5d22d2845a62c935d32cddfe2 # v1.3.3
      with:
        git-push: true
        git-commit-message: "docs(charts): :memo: write updated reademe"

    - name: Push changes
      run: git push